DROP TABLE IF EXISTS statistics;

CREATE TABLE IF NOT EXISTS statistics
(
statistic_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
app varchar NOT NULL,
uri varchar NOT NULL,
ip varchar NOT NULL,
created varchar NOT NULL
);